### ISSUE TITLE
Новый эндпоинт "/hello" 

### ISSUE THREAD

**Issue by MykolaLukashchuk** [AlexandrLOM/storageFirst#2]
Создать новый эндпоинт 
Path: "/hello" 
Метод запроса: GET
Response: "Hello world!"

**Comment by AlexandrLOM** [comment]
получилось, выводит только в JSONе.

**Comment by AlexandrLOM** [comment]
it is finished

**Comment by MykolaLukashchuk** [comment]
Не вижу пулреквеста в мастер ветку для контроля!
